#!/bin/bash

if [ -z "$VERSIONS" ] ; then
	export VERSIONS="$HOME/Dev/Tools/Versions/bin"
	if [ ! -f $VERSIONS ] ; then
		export VERSIONS=$(find -d $VERSIONS -name "Versions")
		echo "Found: $VERSIONS"
	fi
fi

$VERSIONS "$1" "$2" "$3" "$4" "$5" "$6" "$7" "$8" "$9"
